const Data = [
  'Abrar-ul-Haq',
  'Angrej Ali',
  'Kiran Ahluwalia',
  'Dilshad Akhtar',
  'Atif Aslam',
  'Amanat Ali',
  'Shaukat Ali',
  'Ghulam Ali',
  'Naheed Akhtar',
  'Sajjad Ali',
  'Ahmed Rushdi',
  'Abida Parveen',
  'Azra Jehan',
  'Jawad Ahmad',
  'Amrit Maan',
  'Amar Arshi',
  'Pammi Bai',
  'Gurmeet Bawa',
  'Ranjit Bawa',
  'Gurnam Bhullar',
  'Nishawn Bhullar',
  'Narinder Biba',
  'Surjit Bindrakhia',
  'Satwinder Bitti',
  'Bohemia',
  'Jaswinder Brar',
  'Preet Brar',
  'Naseem Begum',
  'Inayat Hussain Bhatti',
  'Benjamin Sisters',
  'Sahir Ali Bagga',
  'Amar Singh Chamkila',
  'Sarbjit Cheema',
  'Humaira Channa',
  'Jaz Dhami',
  'Dev Dhillon',
  'Kulwinder Dhillon',
  'Diljit Dosanjh',
  'Dr Zeus',
  'Attaullah Khan Esakhelvi',
  'Amrinder Gill',
  'Karnail Gill',
  'Nachhatar Gill',
  'Jassi Gill',
  'Gippy Grewal',
  'Ravinder Grewal',
  'Gurshabad',
  'Guru Randhawa',
  'H-Dhami',
  'Hans Raj Hans',
  'Harjit Harman',
  'Mehdi Hassan',
  'Aman Hayer',
  'Kamal Heer',
  'Lehmber Hussainpuri',
  'Yuvraj Hans',
  'Preet Harpal',
  'Labh Janjua',
  'Jasbir Jassi',
  'Lal Chand Yamla Jatt',
  'Jazzy B',
  'Juggy D',
  'Noor Jehan',
  'Kanth Kaler',
  'Kamal Heer',
  'Kanika Kapoor',
  'Karan Aujla',
  'Harshdeep Kaur',
  'Surinder Kaur',
  'Nimrat Khaira',
  'Imran Khan',
  'Nusrat Fateh Ali Khan',
  'Surjit Khan',
  'Farida Khanum',
  'Zubaida Khanum',
  'Rahat Fateh Ali Khan',
  'Hadiqa Kiani',
  'Alam Lohar',
  'Arif Lohar',
  'Babbu Maan',
  'Bhagwant Maan',
  'Gurdas Maan',
  'Harbhajan Maan',
  'K S Makhan',
  'Baljit Malwa',
  'Kuldeep Manak',
  'Shazia Manzoor',
  'Asa Singh Mastana',
  'Daler Mehndi',
  'Veronica Mehta',
  'Mehnaz',
  'Jaspinder Narula',
  'Inderjit Nikku',
  'Musarrat Nazir',
  'Tufail Niazi',
  'Navv Inder',
  'Soni Pabla',
  'Sukhwinder Panchhi',
  'Panjabi MC',
  'Miss Pooja',
  'Fariha Pervez',
  'Abida Parveen',
  'Roshan Prince',
  'Masood Rana',
  'Reshma',
  'Fariha Pervez',
  'Babbal Rai',
  'Saleem Raza',
  'Mohammad Rafi',
  'Bally Sagoo',
  'Surj Sahota',
  'Master Saleem',
  'Didar Sandhu',
  'Hardy Sandhu',
  'Sangtar',
  'Satinder Sartaj',
  'Satinder Satti',
  'Jay Sean',
  'Baba Sehgal',
  'Sukshinder Shinda',
  'Surinder Shinda',
  'Jassi Sidhu',
  'Sardool Sikander',
  'Bikram Singh',
  'Channi Singh',
  'Honey Singh',
  'Happy Raikoti',
  'Jagjit Singh',
  'Malkit Singh',
  'Mickey Singh',
  'Sukhwinder Singh',
  'Tarsame Singh Saini',
  'Lakhwinder Wadali',
  'Manmohan Waris',
  'Ali Zafar',
  'Saieen Zahoor'
]

export default Data