const Data = {
  'wrestlers': [
    { name: 'Adam Rose'},
    { name: 'Alberto Del Rio'},
    { name: 'Alexander Rusev'},
    { name: 'Andre the Giant'},
    { name: 'Arn Anderson'},
    { name: 'Bad News Barrett'},
    { name: 'Barry Horowitz'},
    { name: 'Batista'},
    { name: 'Big Boss Man'},
    { name: 'Big E'},
    { name: 'Big Show'},
    { name: 'Billy Gunn'},
    { name: 'Booker T'},
    { name: 'Bray Wyatt'},
    { name: 'Bret \'Hitman\' Hart'},
    { name: 'Brock Lesnar'},
    { name: 'Brodus Clay'},
    { name: 'Brutus \'The Barber\' Beefcake'},
    { name: 'Cesaro'},
    { name: 'Christian'},
    { name: 'CM Punk'},
    { name: 'Cody Rhodes'},
    { name: 'Curt Hawkins'},
    { name: 'Curtis Axel'},
    { name: 'Damien Sandow'},
    { name: 'Daniel Bryan'},
    { name: 'Darren Young'},
    { name: 'David Otunga'},
    { name: 'Dean Ambrose'},
    { name: 'Diego'},
    { name: 'Dolph Ziggler'},
    { name: 'Drew McIntyre'},
    { name: 'Dwayne \'The Rock\' Johnson'},
    { name: 'Erick Rowan'},
    { name: 'Evan Bourne'},
    { name: 'Fernando'},
    { name: 'George \'The Animal\' Steele'},
    { name: 'Goldust'},
    { name: 'The Great Khali'},
    { name: '\'Hacksaw\' Jim Duggan'},
    { name: 'Heath Slater'},
    { name: 'The Honky Tonk Man'},
    { name: 'Hornswoggle'},
    { name: 'Hulk Hogan'},
    { name: 'The Iron Shiek'},
    { name: 'Jack Swagger'},
    { name: 'Jake \'The Snake\' Roberts'},
    { name: 'Jey Uso'},
    { name: 'Jimmy Uso'},
    { name: 'Jinder Mahal'},
    { name: 'John Cena'},
    { name: 'JTG'},
    { name: 'Junkyard Dog'},
    { name: 'Justin Gabriel'},
    { name: 'Kane'},
    { name: 'Kofi Kingston'},
    { name: 'Koko B. Ware'},
    { name: 'Luke Harper'},
    { name: '\'Macho Man\' Randy Savage'},
    { name: 'Mark Henry'},
    { name: '\'The Million Dollar Man\' Ted DeBiase'},
    { name: 'The Miz'},
    { name: 'Mr. Perfect'},
    { name: 'Paul \'Mr. Wonderful\' Orndorff'},
    { name: '\'Nature Boy\' Ric Flair'},
    { name: 'R-Truth'},
    { name: 'Randy Orton'},
    { name: '\'Ravishing\' Rick Rude'},
    { name: 'Rey Mysterio'},
    { name: 'Ricardo Rodriguez'},
    { name: 'Rob Van Dam'},
    { name: 'Roman Reigns'},
    { name: '\'Rowdy\' Roddy Piper'},
    { name: 'Rusev'},
    { name: 'Ryback'},
    { name: 'Santino Marella'},
    { name: 'Seth Rollins'},
    { name: 'Sgt. Slaughter'},
    { name: 'Shawn Michaels'},
    { name: 'Sheamus'},
    { name: 'Sin Cara'},
    { name: '\'Stone Cold\' Steve Austin'},
    { name: '\'Superfly\' Jimmy Snuka'},
    { name: 'Titus O\'Neil'},
    { name: 'Triple H'},
    { name: 'Tugboat'},
    { name: 'Tully Blanchard'},
    { name: 'Tyson Kidd'},
    { name: 'The Undertaker'},
    { name: 'The Ultimate Warrior'},
    { name: 'William Regal'},
    { name: 'Xavier Woods'},
    { name: 'Yoshi Tatsu'},
    { name: 'Zack Ryder'}
  ]
}

export default Data;